In [1]:
# Task 1: Print Shape & mean temperature per station

# Step 1: Defining the data array

import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

# Step 2: Print the shape of the data

print("Shape of the data array:", data.shape)

# Step 3: Compute and print the mean temperature per station

mean_per_station = np.mean(data, axis=1)
print("Mean temperature per station:", mean_per_station)

Shape of the data array: (4, 5)
Mean temperature per station: [25.3  23.78 26.58 25.26]


In [4]:
# Task 2: Extract temperatures above 28.0°C

# Step 1: Use a boolean mask to filter temperatures

threshold = 28.0
boolean_mask = data > threshold

# Step 2: Extracting the values and print as 1D array

extracted_temperatures = data[boolean_mask]
print("Temperature above 28.0°C:", extracted_temperatures)

Temperature above 28.0°C: [31.2 28.7 30.5 33.1 29.6 31.9 28.1]


In [6]:
# Task 3: Normalize the data to range

# Step 1: Calculate the min and max values of the entire array

data_min = np.min(data)
data_max = np.max(data)

# Step 2: Apply normalization formula given in problem

normalized_data = (data - data.min()) / (data.max() - data.min())

# Step 3: Round the result to 2 decimal places & print

rounded_normalized_data = np.round(normalized_data, 2)
print("Normalized data(rounded to 2 decimal places):")
print(rounded_normalized_data)


Normalized data(rounded to 2 decimal places):
[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
